enum AppWeatherSortEnum {
  LATEST,
  OLDEST,
  HIGHEST_TEMPERATURE,
  LOWEST_TEMPERATURE,
  HIGHEST_PRESSURE,
  LOWEST_PRESSURE,
  HIGHEST_SOLAR_RADIATION,
  LOWEST_SOLAR_RADIATION,
  MOST_RAIN,
  STRONGEST_WIND
}
