enum AppSoilSortEnum {
  LATEST,
  OLDEST,
  HIGHEST_TEMPERATURE50CM,
  LOWEST_TEMPERATURE50CM,
  HIGHEST_TEMPERATURE100CM,
  LOWEST_TEMPERATURE100CM,
  HIGHEST_TEMPERATURE200CM,
  LOWEST_TEMPERATURE200CM,
}
